### ISSUE TITLE
motedem.SDK.InvalidArgument when Scanning

### ISSUE THREAD

**Issue by kilian579** [artgrouplimited/motedem-sdk-python#1]
I've setup the Motedem device in python by following the examples in the ReadMe.

Scanning and emmiting IR sequences worked just fine a few days ago.

**This is the error I'm getting when trying to scan _any device_:**
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/motedem/SDK.py", line 53, in learnAC
    return self.__learn_common__(0x27, ready_callback)
  File "/home/pi/.local/lib/python3.5/site-packages/motedem/SDK.py", line 154, in __learn_common__
    raise InvalidArgument()
motedem.SDK.InvalidArgument

Sometimes the LED switches to a pink color

**Comment by Mikmak50** [comment]
Hi, I have the same issue, did you solve it?

**Comment by kilian579** [comment]
@Mikmak50 No, sry.Still no response from the devs

**Comment by Skandesh** [comment]
Does anyone has an idea why this problem occurs?. Still stuck on the same problem @kilian579 @Mikmak50 @artgrouplimited
